export const skills = [
  {
    id: "teach",
    name: "/teach",
    abbr: "Te",
    layer: "Context",
    color: "#c4636c",
    tagline: "One-time product context setup",
    steps: [
      "Scans your codebase",
      "Asks product questions",
      "Generates .acumen.md",
      "Seeds personas, features, competitors",
    ],
  },
  {
    id: "scout",
    name: "/scout",
    abbr: "Sc",
    layer: "Context",
    color: "#c4636c",
    tagline: "Living competitor map",
    steps: [
      "Maps competitors by JTBD",
      "Direct, indirect & adjacent",
      "Deep analysis mode",
      "Moat & positioning evaluation",
    ],
  },
  {
    id: "persona",
    name: "/persona",
    abbr: "Pe",
    layer: "Context",
    color: "#c4636c",
    tagline: "Behavioral personas from real patterns",
    steps: [
      "Behavior-first, not demographics",
      "Job-to-be-done mapping",
      "Pain points & triggers",
      "Churn & satisfaction signals",
    ],
  },
  {
    id: "features",
    name: "/features",
    abbr: "Fe",
    layer: "Context",
    color: "#c4636c",
    tagline: "Lightweight feature inventory",
    steps: [
      "Scans codebase for features",
      "Maps to personas & metrics",
      "Tracks status & ownership",
      "Identifies gaps & decay",
    ],
  },
  {
    id: "value",
    name: "/value",
    abbr: "Va",
    layer: "Context",
    color: "#c4636c",
    tagline: "Per-persona value & proof metrics",
    steps: [
      "Maps value per persona",
      "Links to north star metrics",
      "Usage signals that prove delivery",
      "Confidence matrix: proven vs assumed",
    ],
  },
  {
    id: "update",
    name: "/update",
    abbr: "Up",
    layer: "Context",
    color: "#c4636c",
    tagline: "Sync latest Acumen skills",
    steps: [
      "Pulls from GitHub",
      "Syncs source/skills/",
      "Updates .agents & .claude",
      "Reports new & removed",
    ],
  },
  {
    id: "orientation",
    name: "/orientation",
    abbr: "Or",
    layer: "Audit",
    color: "#5a9a5a",
    tagline: "Product identity audit",
    steps: [
      "Thesis coherence check",
      "Persona alignment test",
      "Surface breadth vs depth",
      "Positioning exclusion test",
    ],
  },
  {
    id: "defensibility",
    name: "/defensibility",
    abbr: "De",
    layer: "Audit",
    color: "#5a9a5a",
    tagline: "Moat & resilience audit",
    steps: [
      "7 AI-era moat dimensions",
      "Classical moats review",
      "Vulnerability scenarios",
      "Value chain control",
    ],
  },
  {
    id: "diagnose",
    name: "/diagnose",
    abbr: "Di",
    layer: "Ideate",
    color: "#5a8abf",
    tagline: "Find product problems",
    steps: [
      "Value delivery audit",
      "Five Whys with evidence",
      "Feature health check",
      "Reframing lenses applied",
    ],
  },
  {
    id: "measure",
    name: "/measure",
    abbr: "Me",
    layer: "Ideate",
    color: "#5a8abf",
    tagline: "KPI health check",
    steps: [
      "Map metric landscape",
      "North star & input metrics",
      "Bright spots & problems",
      "Value delivery by persona",
    ],
  },
  {
    id: "workshop",
    name: "/workshop",
    abbr: "Wo",
    layer: "Ideate",
    color: "#5a8abf",
    tagline: "Ideation & opportunity discovery",
    steps: [
      "Value chain analysis",
      "Competitive gap scan",
      "User signal synthesis",
      "Ranked opportunity list",
    ],
  },
  {
    id: "roadmap",
    name: "/roadmap",
    abbr: "Ro",
    layer: "Craft",
    color: "#3da63d",
    tagline: "Sequence bets into increments",
    steps: [
      "Organize by strategic themes",
      "Sequence by compounding value",
      "Break into vertical slices",
      "Triage mode for backlogs",
    ],
  },
  {
    id: "increment",
    name: "/increment",
    abbr: "In",
    layer: "Craft",
    color: "#3da63d",
    tagline: "End-to-end increment spec",
    steps: [
      "Context & opportunity",
      "Success metrics & scope tiers",
      "Wireframes & implementation",
      "Engineering considerations",
    ],
  },
  {
    id: "critique",
    name: "/critique",
    abbr: "Cr",
    layer: "Craft",
    color: "#3da63d",
    tagline: "Validate PM artifacts",
    steps: [
      "AI Slop Test (12 tells)",
      "Score across 9 dimensions",
      "Riskiest assumptions found",
      "Ship / tighten / rethink",
    ],
  },
  {
    id: "narrate",
    name: "/narrate",
    abbr: "Na",
    layer: "Communicate",
    color: "#b89430",
    tagline: "Product communication writer",
    steps: [
      "Executive summary",
      "Engineering brief",
      "Customer announcement",
      "Tradeoff negotiation",
    ],
  },
  {
    id: "changelog",
    name: "/changelog",
    abbr: "Ch",
    layer: "Communicate",
    color: "#b89430",
    tagline: "Changelog from commits",
    steps: [
      "Gathers commit history",
      "Grounds in feature context",
      "New / improved / fixed",
      "Benefit-first, jargon-free",
    ],
  },
  {
    id: "cheatsheet",
    name: "/cheatsheet",
    abbr: "Cs",
    layer: "Meta",
    color: "#7a5a9a",
    tagline: "Quick-reference skill card",
    steps: [
      "Lists all 16 commands",
      "Organized by layer",
      "One-line descriptions",
      "Scannable box format",
    ],
  },
];
